Module3 task1
htmlacademy-react/475753-six-cities-8 pull request #4
Opened 2021-10-05 15:49 UTC by Koblizka

2021-10-05 15:53 UTC, what1s1ove requested changes

2021-10-05 15:53 UTC, what1s1ove commented on project/package.json
> +    "react-router-dom": "^5.3.0",
я бы ничего не трогал тут руками, если на лекции не говорили)

2021-10-05 15:53 UTC, what1s1ove commented on project/src/components/not-found/not-found.tsx
> +      <Link to='/'>Back to main page</Link>
```suggestion
      <Link to={AppRoute.Main}>Back to main page</Link>
```
У тебя есть енам. Используй его по максимуму.

2021-10-05 15:57 UTC, Koblizka commented on project/src/components/not-found/not-found.tsx
> +      <Link to='/'>Back to main page</Link>
упустил))

2021-10-05 15:58 UTC, Koblizka commented on project/package.json
> +    "react-router-dom": "^5.3.0",
Я чёто подумал, что у нас не стоит реакт-роут ))

2021-10-06 05:44 UTC, what1s1ove approved these changes

2021-10-06 05:44 UTC, merged